# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 10

image:
  repository: gcr.io/staticweb-test/webapp:v1
  pullPolicy: Always

application:
  name: angular-webapp